import type { WorkspaceLayout } from "./workspace.types";

export const DEFAULT_LAYOUT: WorkspaceLayout = {
  id: "workspace-default",
  name: "Start",
  spalten: 12,
  zeilenHoehe: 80,
  abstand: 12,
  items: [
    {
      id: "panel-schnellnotiz",
      panelTyp: "schnellnotiz",
      titel: "Schnellnotiz",
      x: 0,
      y: 0,
      w: 3,
      h: 2,
    },
    {
      id: "panel-aufgaben",
      panelTyp: "aufgaben",
      titel: "Aufgaben",
      x: 3,
      y: 0,
      w: 3,
      h: 2,
    },
    {
      id: "panel-projektstatus",
      panelTyp: "projektstatus",
      titel: "Projektstatus",
      x: 6,
      y: 0,
      w: 4,
      h: 2,
    },
    {
      id: "panel-toolstart",
      panelTyp: "toolstart",
      titel: "Tool-Start",
      x: 10,
      y: 0,
      w: 2,
      h: 2,
    },
    {
      id: "panel-dateien",
      panelTyp: "dateien",
      titel: "Dateien",
      x: 0,
      y: 2,
      w: 4,
      h: 2,
    },
    {
      id: "panel-letzteInhalte",
      panelTyp: "letzteInhalte",
      titel: "Letzte Inhalte",
      x: 4,
      y: 2,
      w: 4,
      h: 2,
    },
  ],
};
